RANDOM_STATE: 1

EMBEDDING:
  MAX_NUM_WORDS: 30000
  MAX_SEQUENCE_LENGTH: 500
  WORD2VEC_MODEL: "/home/jovyan/Word2Vec/GoogleNews-vectors-negative300.bin.gz"

MODEL:
  BATCH_SIZE: 50
  MAX_EPOCHS: 100
  DROPOUT: 0.5
  RECURRENT_DROPOUT: 0.2
  FILTER_SIZE: 128
  
PREDICT:
  T: 50
